import React from "react";
import {MainWindowWrapper} from "../elements";


export const MainWindow = () => 
{
   return (
   <MainWindowWrapper>
       <div>
       Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi varius consectetur leo a euismod. Integer mollis, odio at maximus sodales, metus mi consectetur urna, vitae efficitur metus odio iaculis ante. Aenean vitae posuere risus. Vivamus finibus lacus erat, et posuere orci commodo in. Nunc sollicitudin tellus orci, vitae pellentesque risus fermentum vel. Aenean id eros lacinia lacus pretium dictum. Nulla maximus aliquam ipsum facilisis auctor. Morbi hendrerit, quam vel laoreet placerat, nibh lacus aliquam orci, at vestibulum ligula velit at sem. Duis sit amet auctor lacus, quis tristique erat. Sed ut faucibus sem. Vestibulum iaculis rutrum nulla, interdum iaculis elit tempor id. Etiam eu orci est. Duis sed est eu dui vestibulum tempor ut non ligula. Integer est sapien, facilisis non luctus id, interdum nec lectus. Nunc hendrerit mi ut turpis porta iaculis. Interdum et malesuada fames ac ante ipsum primis in faucibus.

      Sed tempus non est finibus tincidunt. Donec suscipit, ex ac imperdiet venenatis, est urna aliquet dolor, ut vehicula massa massa ac ipsum. Sed varius vehicula pellentesque. Pellentesque sit amet dignissim felis. Nulla viverra tempus ex, at rutrum lacus accumsan non. Suspendisse lobortis dapibus sem id semper. Nunc sagittis porttitor ex. Maecenas et condimentum enim. Donec ut placerat quam. Curabitur mauris turpis, blandit vitae massa eget, euismod lacinia nisi.

      Mauris cursus tortor ac ultricies aliquet. Praesent luctus ante lorem, id maximus ligula dignissim ut. In ullamcorper libero ac tellus rhoncus scelerisque. Mauris porta, enim sit amet semper lacinia, sem ex elementum sem, sit amet semper orci neque non nunc. Quisque pulvinar elit est, in suscipit urna molestie bibendum. Nunc ultrices volutpat laoreet. In lobortis velit arcu, vitae iaculis libero mattis sit amet. Vivamus posuere finibus lectus, vel interdum ligula tincidunt vitae. Donec consectetur nulla et orci aliquet tempus.

      Cras non sagittis urna, ornare sollicitudin justo. Nulla facilisi. Nunc rutrum massa ut dolor maximus viverra. Etiam placerat scelerisque justo, sed fermentum risus venenatis non. Fusce ac vulputate sem. Morbi id faucibus tellus. Aliquam placerat elementum mauris, eu feugiat arcu egestas sit amet. Suspendisse potenti. Etiam hendrerit dignissim quam, ut sodales justo. Curabitur auctor ante vitae mi laoreet congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum fermentum tellus quis augue tristique sagittis. Aenean fermentum urna nisl, mollis mollis justo egestas nec. Ut nisl magna, posuere ac risus et, bibendum gravida nunc.

      Nunc id ex id enim condimentum finibus vitae id sem. Nullam in urna at arcu vestibulum lacinia id et mi. Phasellus laoreet feugiat orci, id viverra libero volutpat eu. Vivamus dapibus felis eu nunc ornare tempus. Nam auctor nibh at egestas pretium. Phasellus nisl tortor, dignissim eget luctus id, tincidunt in nunc. Aliquam at luctus diam, ut lacinia eros. Praesent ultricies aliquam diam, eget venenatis felis vehicula pellentesque. Sed ac sagittis nulla, ut volutpat odio.

      Donec nec maximus dolor. Etiam consectetur metus et tortor sollicitudin, eget efficitur diam laoreet. Integer non tortor tristique eros suscipit pellentesque non non ligula. Nunc at gravida leo, eu ornare mi. Pellentesque vulputate leo a eros semper, nec convallis nunc consectetur. Praesent et nunc ante. Nulla quis ultricies odio. Phasellus ante ipsum, rutrum id diam sodales, molestie facilisis turpis. Mauris eleifend eleifend libero. In porta elit augue, at pellentesque diam pretium in. Phasellus cursus imperdiet sagittis.

      Fusce sed suscipit tortor, non scelerisque dui. Vestibulum congue metus non quam porttitor, sit amet lobortis libero auctor. Quisque placerat sodales massa quis accumsan. Nullam consectetur elit neque. Proin vitae tincidunt enim, quis fringilla tellus. Etiam quis blandit ligula. Mauris ullamcorper augue vitae mauris consequat, eget volutpat turpis luctus. Mauris sed arcu in magna vehicula imperdiet blandit in ipsum. Curabitur sed ultricies metus. Nulla lorem odio, euismod non elementum quis, efficitur eu sapien. Pellentesque ornare, tortor in mattis euismod, arcu lorem iaculis diam, quis ullamcorper nunc erat et ex. Nam ex est, luctus quis cursus nec, iaculis at mauris. Nam sollicitudin luctus ultricies. Nulla lobortis, libero in aliquam pellentesque, nisl sapien luctus nibh, vel porta felis mi in libero. Integer ultrices volutpat felis quis tristique. Ut ipsum elit, vestibulum at scelerisque porta, gravida vel arcu.

      Aliquam vestibulum fermentum arcu, sed faucibus tortor vehicula ac. Phasellus hendrerit rutrum ante pharetra pharetra. Fusce sollicitudin lacus a magna fermentum lobortis. Maecenas venenatis suscipit rhoncus. Mauris semper ullamcorper est in sodales. Vivamus tempor orci sem. Aenean diam sem, laoreet in enim a, lobortis cursus ipsum. Curabitur purus metus, molestie in purus quis, rhoncus posuere elit. Vivamus viverra ultricies urna quis tincidunt. Aliquam erat volutpat.

      Ut quis dolor ex. Quisque rutrum maximus lectus lobortis pharetra. Praesent sollicitudin velit quis erat rhoncus maximus. Sed eu ligula a justo sagittis dictum. Etiam facilisis ipsum nisi, vel viverra lacus consectetur eu. Nunc eget tincidunt elit. Curabitur vitae orci neque. Sed dapibus eu tortor vitae sodales. Proin quis blandit sapien, sit amet sodales risus. Sed metus felis, scelerisque at hendrerit sit amet, interdum sit amet elit. Suspendisse cursus lectus quis erat lacinia, quis consectetur nisi rutrum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec id augue non ligula blandit dapibus.

      Sed nisi nulla, efficitur nec mauris sed, sagittis efficitur risus. Donec euismod volutpat libero quis pellentesque. Morbi non nunc vitae enim rhoncus pulvinar ut quis massa. Vestibulum nunc tortor, suscipit sed volutpat ut, porttitor ac mi. Mauris neque dolor, imperdiet non risus at, ornare condimentum quam. Donec pharetra nec neque sed porttitor. Nulla vitae mi nisl.

      Aenean id mattis dui. Nullam fermentum risus vel enim elementum ultrices. Cras fringilla pretium scelerisque. Donec erat leo, pulvinar eget eleifend ut, sagittis eu lacus. Maecenas purus urna, cursus et nisl quis, faucibus lacinia libero. Donec augue nisl, gravida quis faucibus commodo, tempor quis arcu. Aliquam erat volutpat. Morbi sodales feugiat leo. Integer egestas aliquet consequat. Aenean fringilla bibendum elementum. Proin mi dolor, faucibus at interdum at, facilisis porttitor nibh. Quisque posuere elit ut metus cursus posuere. Quisque dolor arcu, pulvinar et odio ut, varius egestas ante. Morbi et pellentesque nisl, sit amet laoreet purus. Nunc dictum pulvinar purus, sed iaculis massa tempus vitae.
        </div>
   </MainWindowWrapper>
   );
}